---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: files-api
  name:  files-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: files-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: files-api
    spec:
      nodeSelector:
        exempt: "yes"
      containers:
      - name: files-api
        image: tapis/tapis-files:dev
        command: ["java"]
        args: ["-Xdebug", "-agentlib:jdwp=transport=dt_socket,server=y,address=*:8000,suspend=n", "-cp", "target/tapis-files.jar:target/dependencies/*", "edu.utexas.tacc.tapis.files.api.FilesApplication"]
        imagePullPolicy: Always
        ports:
        - name: "files-api"
          containerPort: 8080
        - name: "files-debug"
          containerPort: 8000
        envFrom:
        - configMapRef:
            name: files-environment-vars
        env:
        - name: TAPIS_SITE_ID
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: siteId
        - name: TOKENS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: service_tenant_base_url
        - name: TENANTS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: service_tenant_base_url
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-files-secrets
              key: rabbitmq-password
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-files-secrets
              key: postgres-password
        - name: SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-files-secrets
              key: service-password
      hostname: files-api
      restartPolicy: Always
