apiVersion: v1
metadata:
  name: files-environment-vars
data:
  LOG_LEVEL: info
  DB_HOST: files-postgres
  DB_NAME: tapisfiles
  DB_USERNAME: tapisfiles
  POSTGRES_DB: tapisfiles
  POSTGRES_USER: tapisfiles
  RABBITMQ_DEFAULT_USER: tapisfiles
  RABBITMQ_DEFAULT_VHOST: tapisfiles
  RABBITMQ_HOSTNAME: files-rabbitmq
  RABBITMQ_USERNAME: tapisfiles
  RABBITMQ_VHOST: tapisfiles
kind: ConfigMap
