---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pgdata
  name: files-pgdata
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 10G
