
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shortsleep
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: shortsleep
        image: mrghort/ubutil
        #command: ["/secrole"]
        command: ["sleep","3600"]
        env:
        - name: VAULT_ADDR
          value: http://vault:8200
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: vault-token
        volumeMounts:
        - name: secrole-script
          mountPath: /secrole
          subPath: secrole
        - name: skadmin-policies
          mountPath: /tmp/skadmin-policies
        - name: sk-policies
          mountPath: /tmp/sk-policies
      volumes:
      - name: secrole-script
        configMap: 
          name: secrole-script
          defaultMode: 0777
      - name: skadmin-policies
        configMap:
          name: skadmin-policies
      - name: sk-policies
        configMap:
          name: sk-policies

