apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        command: ["sleep","3600"]
        image: rabbitmq
        ports:
        - name: rabbitmq
          containerPort: 5672
        volumeMounts:
        - name: rabbitmq-data
          mountPath: "/var/lib/rabbitmq"
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-vol01




