
---
apiVersion: batch/v1
kind: Job
metadata:
  name: renew-sk-secret
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: renew-sk-secret
        command: ["/tmp/renew-sk-secret"]
        #command: ["sleep","3600"]
        image: mrghort/skadminutil:latest
        imagePullPolicy: Always
        env:
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: vault-token
        volumeMounts:
        - name: renew-sk-secret
          mountPath: /tmp/renew-sk-secret
          subPath: renew-sk-secret
      volumes:
      - name: renew-sk-secret
        configMap:
          name: renew-sk-secret
          defaultMode: 0777
